
services:
  api:
    container_name: little-links-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules